
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo_NativeImplementation */

//#ifdef MATHLIBRARY_EXPORTS
#define MATHLIBRARY_API __declspec(dllexport) 
//#else
//#define MATHLIBRARY_API __declspec(dllimport) 
//#endif



#ifndef _Included_jnidemo_NativeImplementation
#define _Included_jnidemo_NativeImplementation
#ifdef __cplusplus
	extern "C" {
#endif
		/*
		* Class:     jnidemo_NativeImplementation
		* Method:    add
		* Signature: (II)I
		*/
		MATHLIBRARY_API JNIEXPORT jint JNICALL Java_jnidemo_NativeImplementation_add
		(JNIEnv *, jobject, jint, jint);

		/*
		* Class:     jnidemo_NativeImplementation
		* Method:    multiply
		* Signature: (II)I
		*/
		MATHLIBRARY_API JNIEXPORT jint JNICALL Java_jnidemo_NativeImplementation_multiply
		(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
	}
#endif
#endif
